import io
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from app.models.final_trip_request import ItineraryOption, FlightOption

_DARK = colors.HexColor("#2D2D2D")
_TAN = colors.HexColor("#C9A96E")
_LIGHT_BG = colors.HexColor("#F8F5F0")


def generate_itinerary_pdf(itinerary: ItineraryOption, flights: list[FlightOption]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter,
                            leftMargin=0.75 * inch, rightMargin=0.75 * inch,
                            topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle("Title", parent=styles["Normal"],
                                 fontSize=22, textColor=_DARK, spaceAfter=4,
                                 fontName="Times-Roman")
    subtitle_style = ParagraphStyle("Subtitle", parent=styles["Normal"],
                                    fontSize=11, textColor=colors.HexColor("#888888"),
                                    spaceAfter=16, fontName="Times-Italic")
    section_style = ParagraphStyle("Section", parent=styles["Normal"],
                                   fontSize=13, textColor=_DARK, spaceBefore=18,
                                   spaceAfter=8, fontName="Helvetica-Bold")
    body_style = ParagraphStyle("Body", parent=styles["Normal"],
                                fontSize=9, textColor=_DARK, leading=14)

    story = []

    # Header
    destination = itinerary.days[0].area if itinerary.days else "Your Trip"
    date_range = ""
    if itinerary.days:
        date_range = f"{itinerary.days[0].date}  –  {itinerary.days[-1].date}"

    story.append(Paragraph(f"{destination} &mdash; {itinerary.style}", title_style))
    story.append(Paragraph(f"{date_range}  ·  {itinerary.description}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=_TAN, spaceAfter=12))

    # Itinerary days
    story.append(Paragraph("ITINERARY", section_style))
    for day in itinerary.days:
        day_data = [["Day", "Time", "Activity", "Place", "Food"]]
        for slot_name, slot in [("Morning", day.morning), ("Afternoon", day.afternoon), ("Evening", day.evening)]:
            if slot:
                day_data.append([
                    f"Day {day.dayNumber}" if slot_name == "Morning" else "",
                    slot_name,
                    slot.activity or "",
                    slot.place or "",
                    slot.foodSuggestion or "",
                ])
        if len(day_data) > 1:
            t = Table(day_data, colWidths=[0.7 * inch, 0.8 * inch, 2.3 * inch, 1.8 * inch, 1.5 * inch])
            t.setStyle(_day_table_style())
            story.append(t)
            story.append(Spacer(1, 6))

    # Flights
    story.append(Paragraph("FLIGHTS", section_style))
    flight_data = [["#", "Airline", "Flight", "Route", "Depart", "Return", "Duration", "Price"]]
    for f in sorted(flights, key=lambda x: x.rank):
        flight_data.append([
            str(f.rank),
            f.airline,
            f.flightNumber or "—",
            f"{f.origin} → {f.destination}",
            f"{f.departureDate} {f.departureTime}",
            f"{f.returnDate} {f.returnTime}",
            f"{f.duration}h",
            f"${f.price}",
        ])
    ft = Table(flight_data, colWidths=[0.3 * inch, 1.0 * inch, 0.7 * inch, 1.1 * inch,
                                        1.3 * inch, 1.3 * inch, 0.6 * inch, 0.6 * inch])
    ft.setStyle(_generic_table_style())
    story.append(ft)

    # Hotels
    story.append(Paragraph("HOTELS", section_style))
    hotel_data = [["Area", "Nights", "Hotel", "Type", "Rating", "Per Night", "Total"]]
    for stop in itinerary.hotelStops:
        for hotel in stop.hotels:
            hotel_data.append([
                stop.area, str(stop.nights),
                hotel.name, hotel.type or "—",
                str(hotel.rating),
                f"${hotel.pricePerNight:.0f}",
                f"${hotel.totalPrice:.0f}",
            ])
    ht = Table(hotel_data, colWidths=[1.2 * inch, 0.5 * inch, 1.5 * inch, 1.0 * inch,
                                       0.5 * inch, 0.8 * inch, 0.7 * inch])
    ht.setStyle(_generic_table_style())
    story.append(ht)

    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by AI Travel Planner", body_style))

    doc.build(story)
    return buf.getvalue()


def _day_table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 1), (-1, -1), _LIGHT_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ])


def _generic_table_style() -> TableStyle:
    return TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _DARK),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, _LIGHT_BG]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ])
